source 'https://rubygems.org'

gem 'activesupport', '~> 4.2.1'
gem 'activemodel', '~> 4.2.1'
gem 'annotate-sequel', '~> 1.1.0'
gem 'faker', '~> 1.4.3'
gem 'grape', '~> 0.11.0'
gem 'grape-active_model_serializers', '~> 1.3.2'
gem 'grape-entity', '~> 0.4.5'
gem 'rack-cors', '~> 0.4.0', :require => 'rack/cors'
gem 'require_all', '~> 1.3.2'
gem 'sequel', '~> 4.22.0'
gem 'sequel_secure_password', '~> 0.2.12'
gem 'sqlite3'
gem 'warden-oauth2', '~> 0.0.1'
gem 'will_paginate', '~> 3.0.6'

group :test do
  gem "factory_girl", "~> 4.0"
  gem 'mocha', '~> 1.1.0'
  gem 'rack-test', '~> 0.6.3', require: 'rack/test'
end

